# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in -o requirements.txt --index-strategy unsafe-best-match --python-platform=linux
bulk-geocoding==0.1.1
    # via -r requirements.in
cachetools==5.3.3
    # via google-auth
certifi==2024.7.4
    # via requests
chardet==3.0.4
    # via requests
google-api-core==1.34.1
    # via
    #   google-cloud-bigquery
    #   google-cloud-core
google-auth==2.31.0
    # via
    #   google-api-core
    #   google-auth-oauthlib
    #   google-cloud-bigquery
    #   google-cloud-core
google-auth-oauthlib==0.5.3
    # via -r requirements.in
google-cloud-bigquery==3.20.1
    # via -r requirements.in
google-cloud-core==2.4.1
    # via google-cloud-bigquery
google-crc32c==1.5.0
    # via google-resumable-media
google-resumable-media==1.3.3
    # via google-cloud-bigquery
googleapis-common-protos==1.63.2
    # via
    #   google-api-core
    #   grpcio-status
grpcio==1.64.1
    # via
    #   google-api-core
    #   grpcio-status
grpcio-status==1.48.2
    # via google-api-core
idna==2.10
    # via requests
numpy==2.2.3
    # via pandas
oauthlib==3.2.2
    # via requests-oauthlib
packaging==21.3
    # via google-cloud-bigquery
pandas==2.2.3
    # via -r requirements.in
protobuf==3.20.3
    # via
    #   google-api-core
    #   googleapis-common-protos
    #   grpcio-status
pyasn1==0.6.0
    # via
    #   pyasn1-modules
    #   rsa
pyasn1-modules==0.4.0
    # via google-auth
pyparsing==3.1.4
    # via packaging
python-dateutil==2.9.0.post0
    # via
    #   google-cloud-bigquery
    #   pandas
pytz==2025.1
    # via pandas
requests==2.25.0
    # via
    #   bulk-geocoding
    #   google-api-core
    #   google-cloud-bigquery
    #   requests-oauthlib
requests-oauthlib==2.0.0
    # via google-auth-oauthlib
rsa==4.9
    # via google-auth
six==1.16.0
    # via
    #   google-resumable-media
    #   python-dateutil
tzdata==2025.1
    # via pandas
urllib3==1.26.5
    # via requests
